require 'opal'
require 'opal-browser'

desc "Build our app to test.js"
task :build do
  Opal.append_path 'app'
  builder = Opal::Builder.new(prerequired: ['opal', 'browser'])
  File.binwrite "test.js", builder.build("test").to_s
end
